---

- name: dependencies are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-bcrypt
    - python-passlib
    - python-ldap
    - python-setuptools
    - python-dev
    - libffi-dev
    - rsyslog
