---

- name: dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - python3-vobject
    - python3-dateutil
    - python-bcrypt
    - python-passlib
    - python-ldap
    - python-setuptools
    - python-dev
    - libffi-dev
    - rsyslog
    - git-core

- name: radicale is downloaded
  git:
    repo: "{{ radicale_git_url }}"
    version: "{{ radicale_version }}"
    dest: "{{ radicale_download_dir }}"
    update: true
    depth: 1
  notify: restart radicale

- name: radicale in PATH
  file:
    state: link
    path: /usr/local/bin/radicale
    src: "{{ radicale_download_dir }}/radicale.py"
    owner: root
    group: root
    mode: 755
